apiVersion: v1
kind: ConfigMap
metadata:
  name: moviesapi_config
data:
  DB_NAME: MoviesApiDb
  DB_USER: sa
  DB_HOST: ""

---

apiVersion: v1
kind: Secret
metadata:
  name: moviesapi_secrets
type: Opaque
data:
  DB_PASSWORD: MVN0cm9uZ1B3ZCEh

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: moviesapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: moviesapi
  template:
    metadata:
      labels:
        app: moviesapi
    spec:
      containers:
      - name: moviesapi_container
        image: ivancekikj/movies-api:latest
        ports:
        - containerPort: 80
        env:
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: moviesapi_config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: moviesapi_config
              key: DB_USER
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: moviesapi_config
              key: DB_HOST
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: moviesapi_secrets
              key: DB_PASSWORD