apiVersion: v1
kind: Service
metadata:
  name: moviesapi_service
  labels:
    app: moviesapi
spec:
  selector:
    app: moviesapi
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP