apiVersion: v1
kind: Secret
metadata:
  name: sqlserverdb-secrets
  namespace: main
type: Opaque
data:
  DB_PASSWORD: MVN0cm9uZ1B3ZCEh

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: sqlserverdb-config
  namespace: main
data:
  ACCEPT_EULA: "Y"

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sqlserverdb
  namespace: main
spec:
  serviceName: sqlserverdb-service
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      containers:
      - name: sqlserver
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
        - containerPort: 1433
          name: sql
        env:
        - name: ACCEPT_EULA
          valueFrom:
            configMapKeyRef:
              name: sqlserverdb-config
              key: ACCEPT_EULA
        - name: MSSQL_SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sqlserverdb-secrets
              key: DB_PASSWORD
        volumeMounts:
        - name: mssql-data
          mountPath: /var/opt/mssql
  volumeClaimTemplates:
  - metadata:
      name: mssql-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

---

apiVersion: v1
kind: Service
metadata:
  name: sqlserverdb-service
  namespace: main
spec:
  type: LoadBalancer
  selector:
    app: sqlserver
  ports:
  - port: 1433
    protocol: TCP
    name: sql
